### ISSUE TITLE
gpg problem

### ISSUE THREAD

**Issue by janhoustek** [renekliment/turris-lxc-howto#1]
Pri spusteni root@debian1:/# gpg --keyserver pgpkeys.mit.edu --recv-key B4C86482705A2CE1
Jsem dostal tento vystup:
gpg: directory '/root/.gnupg' created
gpg: can't open '/usr/share/gnupg/dirmngr-conf.skel': No such file or directory
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

Pomohlo toto:
root@debian1:/# apt remove gnupg
root@debian1:/# apt install --reinstall gnupg2

**Comment by renekliment** [comment]
Hm, to je divné. Až budu u Turrisu tak ještě přezkouším, jestli se to samo neopravilo, případně upravím návod. Bohužel jsem si po nové instalaci nepovolil vzdálený přístup na firewallu.

Díky za nahlášení.

**Comment by renekliment** [comment]
Opraveno. Nyní se celá klíčenka debian-ports instaluje již při debootstrapu.
Také bylo změněno pár jiných věcí v návodu. Ještě jednou díky za nahlášení.
